### ISSUE TITLE
Ink file gets locked by Unity

### ISSUE THREAD

**Issue by klootas** [inkle/ink-unity-integration#102]
Unity is often locking my ink file preventing me from saving it...
Here's what I do:
1. Edit and save in editor
2. Switch back to Unity which now compiles the ink (successfully)
3. Edit and save in editor - Boom I get this message (in VS Code):

"Failed to save 'MyFile.ink': Unable to write file 'Assets\MyFile.ink'
(Unknown (FileSystemError): Error: EBUSY: resource busy or locked, open 'Assets\MyFile.ink')"

It keeps locked for a minute or so, the only way that I found to reliably break the lock is to play the game... Any idea as to what is going on?

Version: 0.9.22
Unity: 2019.3.9

Thanks!

**Comment by kwi-dk** [comment]
Presumably the file is opened but not explicitly closed, so it takes a garbage collection to release the lock.

Something like this may be all that's needed, though I have not tested it _at all_:

```
diff --git i/Assets/Plugins/Ink/Core/Editor/Ink Library/InkMetaFile.cs w/Assets/Plugins/Ink/Core/Editor/Ink Library/InkMetaFile.cs
index 5e0e39a..95809c0 100644
--- i/Assets/Plugins/Ink/Core/Editor/Ink Library/InkMetaFile.cs 
+++ w/Assets/Plugins/Ink/Core/Editor/Ink Library/InkMetaFile.cs 
@@ -200,7 +200,8 @@ namespace Ink.UnityIntegration {
                                Debug.LogWarning("Ink file asset is null! Rebuild library using Assets > Rebuild Ink Library");
                                return "";
                        }
-                       return File.OpenText(inkFile.absoluteFilePath).ReadToEnd();
+                       using (var reader = File.OpenText(inkFile.absoluteFilePath))
+                               return reader.ReadToEnd();
                }
 
                public void ParseContent () {
```

Try and see if that fixes it, and report back?

**Comment by klootas** [comment]
Tried it and it works perfectly!
You can even just do one line change to fix it:
-                       return File.OpenText(inkFile.absoluteFilePath).ReadToEnd();
+                      return File.ReadAllText(inkFile.absoluteFilePath);

Thank you so much @kwi-dk! 👊🤗

**Comment by joethephish** [comment]
Amazing. We should definitely integrate this fix @tomkail! Thanks @kwi-dk!

**Comment by tomkail** [comment]
Great find! That's in now
