### ISSUE TITLE
Ink recompilation takes a long time in large projects (cross-post)

### ISSUE THREAD

**Issue by Liance** [inkle/ink-unity-integration#109]
This is a cross-post of the work patrickklug did on documenting this bug - they just posted it in the main Ink repository.

https://github.com/inkle/ink/issues/608

> I'm having a problem where Recompiling the Ink library in my project takes AGES...
> It seems that every single .ink file, regardless of how small it is, takes about 75 seconds to import. We have 55 files currently in the project and there will be 100s more in the future.
> 
> If I take the same files and push them into a new project, they all compile in about five seconds instead.
> 
> We have no local modifications to ink. From what I can gather, the only difference is the size of the project. From debugging the problem it seems that the calls to AssetDatabase.ImportAsset and InkLibrary.Save()as part of the InkCompiler:CompileInkInternal (which is called once per file) are the slow bits.
> 
> Is this a known issue?

The answer appears to be: "maybe?"

There have been similar bugs related to compilation reported on discord [in the past](https://discordapp.com/channels/329929050866843648/329932369530454016/688424636701999320), but it seems like a fix had been applied - and the but wasn't *quite* like this one.

(I've added a screenshot of the developer response for context)
![image](https://user-images.githubusercontent.com/3412295/85498334-64164a80-b5d7-11ea-9828-f464a575aad5.png)
![image](https://user-images.githubusercontent.com/3412295/85498358-70020c80-b5d7-11ea-9066-e99784aca9c2.png)

It's worth mentioning that the "55 ink files and counting" use case seems unusual (though it shouldn't be causing problems).

**Comment by patrickklug** [comment]
I ended up working around this somewhat by hacking the InkCompiler to process all ink files first and then in the end call `AssetDatabase.Refresh()` and `InkLibrary.Save()`. This makes Recompiling the ink library be done in seconds.

Purely for demonstration purposes (it's quite hacky):

https://github.com/patrickklug/ink-unity-integration/commit/40ba511b6f76530dc6ee1a1eeb3464bf07c8f71c

Combined with disabling the autocompile this solves most of my woes but there's still something odd going where the Ink library asset hangs forever when first building the Library folder.

**Comment by tomkail** [comment]
Ah! Right I think I understand. This is the product of having lots of ink files in a single project. At Inkle we tend to just have a single master ink file, so we'd never noticed!
The crux of the issue, as far as I can tell, is that InkLibrary.Save calls AssetDatabase.SaveAssets(), which is quite slow. Doing this 100x (as each file compiles) is VERY slow.
I wanted it to save because it's fairly important that the ink library is solidly up-to-date, and it's important that it reflects the actual files that actually exist - but on reflection I'm not sure a 3rd party API should ever be saving assets. For now I'm going to test without AssetDatabase.SaveAssets() and see what issues I run into, and if that works I'll remove it from the codebase.

**Comment by joethephish** [comment]
Quick clarification: at inkle, we generally have a single **root** ink file, and lots of include ink files - e.g. Heaven's Vault has 162 ink files altogether, but we only need to compile once, hence what @tomkail mentioned about only having to call AssetDatabase.SaveAssets() once.

**Comment by patrickklug** [comment]
that would make sense. in Tavern Keeper (the project where I'm seeing this issue) we structured our interactive fiction so that each separate conversation is a standalone ink file which we then organize in our own node-based visual story planner.

**Comment by tomkail** [comment]
I've pushed a fix to the development branch - it fixes the issue in a slightly different way, so I'm curious to compare performance!

**Comment by patrickklug** [comment]
Compilation now completes in a second!
And it seems to solve the issue where importing the Ink library asset would just hang forever when I first startup the game (with no Library folder created yet).

👍👍👍
