### ISSUE TITLE
Make compiled JSON a sub asset of .ink files.

### ISSUE THREAD

**Issue by tomkail** [inkle/ink-unity-integration#11]
To keep the assets hierarchy panel a bit clearer, I'd like to nest compiled JSON inside of the .ink file as a child, in the same way that a sprite is a child of a texture.
I've had a tinker, but failed to get this working - it's not a particularly well documented feature.
If it's the case that you can't nest in files that aren't ScriptableObjects, suggest that we instead convert InkFile to a ScriptableObjects and nest both the .ink and the .json inside of it. This would be a pretty massive change, so we're in no rush.
I'd like to hear any thoughts on this problem, if you've got them!

**Comment by joethephish** [comment]
Interesting idea, but wouldn't that mean that there would be no clear way to edit an ink file, since it'd be nested inside a ScriptableObject...?!

**Comment by tomkail** [comment]
The file would be visible, like this - 
![image](https://cloud.githubusercontent.com/assets/1252816/15435395/cc759b0e-1eb3-11e6-8147-2899f5eba9c5.png)

**Comment by joethephish** [comment]
And what would the structure be like in the native file system?

**Comment by tomkail** [comment]
I actually don't know! I'd imagine (referencing the texture/Sprite setup)
that they're stored in the master asset - but I'm not sure! It's something
to find out. This is definitely a big job, if it works, which is why I've
not tried it yet. There's not really *that* much payoff, but it could,
theoretically, be better than what we have.

**Comment by tomkail** [comment]
This wouldn't actually be desirable, since it'd force users to also ship their ink!
