### ISSUE TITLE
Loading .ink files directly

### ISSUE THREAD

**Issue by jhocking** [inkle/ink-unity-integration#111]
I just started using Ink for a new project, and the Unity integration has all kinds of tooling around converting to JSON. But after some digging I found I could load .ink files directly:

```
// inkFileContents: linked TextAsset, or Resources.Load, or even StreamingAssets
var compiler = new Ink.Compiler(inkFileContents);
Ink.Runtime.Story story = compiler.Compile();
Debug.Log(story.Continue());
```
Is this a bad approach? Seems much more convenient, so I'm just wondering if there's a compelling reason I shouldn't do it this way.

Like, I'm guessing the compiler generates a lot of garbage and that's why they normally precompile the stories. Is that the reason? Because I don't really care about that; I won't be doing this in high-performance parts of the game so garbage collection isn't a problem.

**Comment by tomkail** [comment]
You’re totally free to do that, if you want! I personally wouldn’t though,
it’s very inefficient and the tool is set up to handle compilation
automatically. What are the advantages you see doing it like this?

**Comment by jhocking** [comment]
The main reason is just that it's more convenient. That's not a strong reason, but if there isn't a compelling reason _not_ to then I'd rather do what's most convenient, hence why I asked this question.

To elaborate a bit more, there are two big convenience factors for my project. One is that we have a lot of small .ink files, resulting in a lot of additional noise (versus a single JSON file that gets compiled). Rather than using Ink for a single narrative running throughout the game, we've got lots of little narrative snippets.

The other is modding support. We're purposely putting all the Ink in StreamingAssets to make it easy for people to modify the game's content. Here again, modders could generate compiled files, but it's simpler for everything to just be .ink files.

**Comment by tomkail** [comment]
Mod support is definitely a good case for this! We only opened up the
compiler to the runtime recently, exactly for that reason.
Curious to hear what makes it generally more convenient from your
perspective though, my goal for the package was for users to be able to
basically ignore the compiler. It should deal fine with having lots of
separate stories - they’ll only compile if they change. Any feedback for us
on that point?
Ta!

**Comment by jhocking** [comment]
Well it's just a hassle to handle all the files. In particular, our game requires them to be in a specific directory structure (eg. so it can load just the inks for area 1, just area 2, etc.) or I'd use the "New JSON Path" setting. I suppose this requirement could be dealt with by having optional overrides for that setting (if the .ink is in directory X then compile to directory Y) but frankly I doubt implementing that feature is worth it.

Anyway I was mostly wondering if there's a serious problem that I need to know about, and it sounds like there isn't. It may be worth just adding a subheading like this to the readme:

**Loading Ink files directly**

Precompiling your stories is more efficient so that's recommended over loading .ink at runtime. That said, it's a useful approach for some situations, and is easily done with the following code:

```
// inkFileContents: linked TextAsset, or Resources.Load, or even StreamingAssets
var compiler = new Ink.Compiler(inkFileContents);
Ink.Runtime.Story story = compiler.Compile();
Debug.Log(story.Continue());
```

**Comment by tomkail** [comment]
Cool, that’s good info! I’ll nab that for the docs too :D

**Comment by jhocking** [comment]
Another thing I just realized is that Ink includes (y'know, INCLUDE yada.ink) is complicated by this approach. That's something to note as well in the documentation where this approach is mentioned.
https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#using-the-compiler

That code snippet will ignore includes. To handle includes when compiling, search for UnityInkFileHandler in the compiler code. That first line is expanded out to:
var compiler = new Ink.Compiler(inputString, new Compiler.Options
{
	countAllVisits = true,
	fileHandler = new UnityInkFileHandler(Path.GetDirectoryName(inkAbsoluteFilePath))
});

If you want to compile at runtime (especially for modding) then just swap in that expanded code, plus you'll need to copy/paste the private UnityInkFileHandler class. This will only work with StreamingAssets though, and not on platforms like WebGL where the file loading is different from PC/Mac. If you're a good programmer then you can modify the InkFileHandler to work with Resources.Load instead of traditional file IO, but at that point you gotta wonder if supporting INCLUDE is even worth it.

**Comment by tomkail** [comment]
Thanks! I've made that class public and moved it outside Editor, and made a note. Feel free to make pull requests if you see something unclear or that needs fixing :)
