### ISSUE TITLE
Unity 2020 fails using deterministic compilation

### ISSUE THREAD

**Issue by klootas** [inkle/ink-unity-integration#113]
Hi there!
For some reason I need to turn off deterministic compilation in Unity 2020, here's the compile time error:

Deterministic compilation failed. You can disable Deterministic builds in Player Settings
Assets\Plugins\Ink\InkLibs\InkCompiler\Properties\AssemblyInfo.cs(22,29): error CS8357: The specified version string contains wildcards, which are not compatible with determinism. Either remove wildcards from the version string, or disable determinism for this compilation

**Comment by tomkail** [comment]
Thanks for the report, fixed on latest!

**Comment by RWOverdijk** [comment]
This might be a dumb question, but how do I get latest? It hasn't been pushed to the assetstore yet, has it?

**Comment by tomkail** [comment]
No, I rarely update that (it’s a pain). You can download a zip of the
project on the github page. Try our discord if you need more help!
