### ISSUE TITLE
Use new Progress API during compilation

### ISSUE THREAD

**Issue by joshrickert** [inkle/ink-unity-integration#117]
Unity 2020 includes the new [Progress API](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/Progress.html). This seems like a great fit for Ink compilation.

**Comment by tomkail** [comment]
Oh that looks perfect! If someone else wants to do this it’d be great, I
won’t have time for a while.

**Comment by tomkail** [comment]
This is done!
