### ISSUE TITLE
Unity Package Manager support

### ISSUE THREAD

**Issue by danielheim** [inkle/ink-unity-integration#118]
This is mainly a request. But it would be great if I could install the library via Unity Package Manager.
https://docs.unity3d.com/Manual/CustomPackages.html

**Comment by tomkail** [comment]
There's an issue open for that here :) We don't have the time, unfortunately, but if you feel like solving it let us know and we'll merge it in! https://github.com/inkle/ink-unity-integration/issues/84

**Comment by danielheim** [comment]
Thanks, sorry I completely missed that yesterday.
