### ISSUE TITLE
Ink compiler appears to be included in Unity builds

### ISSUE THREAD

**Issue by rhys-vdw** [inkle/ink-unity-integration#119]
As far as I can tell the ink compiler code (`InkCompiler/**/*.cs`) is bundled into the [`Ink-Libraries` asmdef](https://github.com/inkle/ink-unity-integration/tree/17b80e5c8294cf37aac439b3d014101fc3ac5783/Assets/Plugins/Ink/InkLibs), which is set to build on all platforms.

Given that the normal use-case is to compile developer-generated assets, I suggest that it is moved into an editor-only assembly.

**Comment by tomkail** [comment]
Ah this is by design - but perhaps we could make it optional somehow, since
it’s certainly a rare use case.

**Comment by rhys-vdw** [comment]
It'd just be a matter of putting the compiler stuff in an editor-only assembly and letting users change the available platforms on its asmdef should they want to include the compiler in a build.

I think given ppl (including myself) build for WebGL it's worth excluding this by default. Building a compiler tool seems like an advanced use case.
