### ISSUE TITLE
Hide the InkLibrary asset

### ISSUE THREAD

**Issue by tomkail** [inkle/ink-unity-integration#12]
Given that it's not meant to be deleted, moved or renamed, I feel it would be best to hide the InkLibrary asset in the inspector, and instead only make it viewable via Edit > Ink. This mimics the behaviour of other Unity project settings, such as input.
I've had a quick stab, but failed to get it working. If anybody has experience with HideFlags, feel free to have a go!

**Comment by KumoKairo** [comment]
I'm pretty positive that it's not possible to make a "root" asset invisible with HideFlags. It's working only on "internal" or "nested" assets inside a file that were included using AssetDatabase.AddObjectToAsset (https://docs.unity3d.com/ScriptReference/AssetDatabase.AddObjectToAsset.html)

I propose a solution - if we can't hide an asset from Unity's project folder, we should place a plaintext YAML or JSON file at the root of the Project (where the .csproj files are usually generated) and access it through the PreferenceItem (https://docs.unity3d.com/ScriptReference/PreferenceItem.html)
It will look like this:
![image](https://user-images.githubusercontent.com/2943071/40674643-1dd33c70-637e-11e8-8f5e-781bfc6d6a40.png)

Or from an "Edit > Ink" menu item like you've described.

Using an external (non-asset) file is pretty common solution for a library-project-wise preferences. It won't be visible directly to the users (no way to accidentally delete it in the Unity's Project view), but it will be shared with the version control, so every user would have the latest version.

**Comment by tomkail** [comment]
Whoa these are unity features I’m not aware of!
So I won’t be making major changes for a while (Heaven’s Vault is nearing
the end of development) but if anyone wanted to make these changes they
found promising!

**Comment by KumoKairo** [comment]
@tomkail There's still an open answer about the goals behind the Ink Library. Can you tell us how and why have Inkle decided to implement it?

**Comment by tomkail** [comment]
So the one other thing that the InkLibrary does is keep track of the files that are currently being compiled. It's important that this is stored in some kind of asset because if Unity recompiles script assemblies (like when you edit a file) that data can otherwise be lost. 
We could absolutely keep this data in the file you propose creating though!

**Comment by tomkail** [comment]
Fixed
