### ISSUE TITLE
Ink library rebuilds on every Unity startup

### ISSUE THREAD

**Issue by patrickklug** [inkle/ink-unity-integration#139]
Seems that every time I start Unity the ink library gets rebuild which takes about half a second and slows down opening the Unity editor.

**Comment by tomkail** [comment]
It’s been doing this a while, I believe - but perhaps it’s not necessary
any more? It was to make sure it was always up to date on launch.

**Comment by tomkail** [comment]
We now validate rather than rebuild, meaning it'll only rebuild if it needs to.
