### ISSUE TITLE
Specifying variables or INCLUDEs at the start of the file results in unplayable story

### ISSUE THREAD

**Issue by isakgrozny** [inkle/ink-unity-integration#14]
If I specify a variable or an INCLUDE (or any non-knot object, really) at the start of story.ink, the compiled file can't be played in the Ink Player.

I'm using the latest version of Ink-Unity-Integration, plus Unity 5.3.4f1 (personal).

**Comment by joningold** [comment]
This seems unlikely: is it that you're missing an initial divert? For
instance, in the following

VAR x = "Hello"

=== knot
{x}
-> END

it'll not enter that "knot" unless there's an explicit "-> knot" between
the VAR and the === knot == definition. (but it will auto-enter that knot
if its the first thing it encounters.)

cheers
jon

**Comment by isakgrozny** [comment]
Ohhh. Right, seems I was misreading the instructions. Thank you for clearing it up!
