### ISSUE TITLE
Ink settings being reset 

### ISSUE THREAD

**Issue by rhys-vdw** [inkle/ink-unity-integration#143]
Often while changing branches, rebasing or merging we're having a problem where our ink settings `defaultJsonAssetPath` is getting reset to "none". Likely the entire `InkSettings.asset` is being reset to default, but that's the only setting we've changed.

This is causing problems, especially with the less technical people on the team who can't work out why their story changes aren't being reflected in game (wrong JSON file being modified).

![image](https://user-images.githubusercontent.com/822105/101559876-32266280-3a16-11eb-99c5-0b9b311b82c3.png)

Version: 0.9.61

**Comment by tomkail** [comment]
I've been keeping an eye out for this and I've not seen it yet. Has it been affecting you still?

**Comment by rhys-vdw** [comment]
Yeah, it's happened a few times. I've not been working on the project for the last couple of weeks though. I'll update this issue if it comes up again.

**Comment by tomkail** [comment]
Don't suppose you've seen this recently? If not, I'll close it

**Comment by rhys-vdw** [comment]
We've moved onto a project that doesn't use ink, so I have not really had a chance to see it in the last year. Tbh I don't remember making this issue. I'm sure if somebody else encounters the same problem you can reopen.
