### ISSUE TITLE
Batch recompile times out on every other Ink file

### ISSUE THREAD

**Issue by dcastalia-personal** [inkle/ink-unity-integration#145]
After updating a project to Unity 2020.2.0f1 and Ink Unity Integration 0.9.61 (UPM), the Ink compiler exhibits odd behavior: when Assets > Recompile Ink is performed, _every other_ Ink file times out with the following error:

```
Ink Compiler timed out for /Users/MyUserName/MyProjectPath/Assets/Adam Applebaum.ink.
Compilation should never take more than a few seconds, but for large projects or slow computers you may want to increase the timeout time in the InkSettings file.
If this persists there may be another issue; or else check an ink file exists at this path and try Assets/Recompile Ink, else please report as a bug with the following error log at this address: https://github.com/inkle/ink/issues
Error log:

UnityEngine.Debug:LogError (object)
Ink.UnityIntegration.InkCompiler:Update () (at Library/PackageCache/com.inklestudios.ink-unity-integration@0.9.61/Editor/Core/Compiler/InkCompiler.cs:112)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)
```

After waiting for each timeout, the completion log is printed to the console and reports that the other half of the files were successfully compiled.

I can compile one file at a time just fine.  It's only when I have to compile more than one at once that this happens.

**Comment by tomkail** [comment]
Ooh that’s a new one. If you can, please try the development branch and see
if it fixes your issue - otherwise if you’re able to send me your ink I’ll
have a look at it.

**Comment by dcastalia-personal** [comment]
Thanks, Tom!  I reproduced it in the development version of Ink in an empty Unity project with empty Ink files, which you can DL here <https://www.dropbox.com/s/djrnrvqr539l9cr/Ink%20Compile%20Timeout.zip?dl=0>.

The only step to reproduce is to open the project in Unity 2020.2.0f1 and choose Assets > Recompile Ink.

**Comment by klootas** [comment]
I'm having the same issue in Unity 2020.2. I'm also getting the dreaded "Assertion failed on expression: 'm_DisallowAutoRefresh >= 0'" error, but maybe that's a side effect of not being able to compile.

**Comment by tomkail** [comment]
Replicated with 0.9.61, but fortunately this seems resolved with 0.9.7 (latest on development branch).
Can I suggest you move over to that version and let me know how you get on? I'd like to push it to master but I wouldn't mind a bit more testing first - do let me know if you have issues!

There's a fix for the DisallowAutoRefresh bug in there too, although that one is a bit trickier to work out so I can't promise it'll resolve it!

**Comment by tomkail** [comment]
I have a fix for both issues - will push to the development branch tomorrow.

**Comment by tomkail** [comment]
Pushed to dev! Please test and let me know :)

**Comment by dcastalia-personal** [comment]
Testing the latest commit in dev (77cafeca0b6b9e3d83724bfbaa0a7537aba70323), I'm now seeing Recompile All start and never complete.  So there's no timeout anymore after x seconds.

I've updated the repro link above with a version of the project on the latest version.  Thanks for the quick turnaround!

**Comment by tomkail** [comment]
Right! Try again :)

**Comment by dcastalia-personal** [comment]
Latest fixes the issue for me.  Thank you!
