### ISSUE TITLE
Unity Package Manager Git

### ISSUE THREAD

**Issue by MylesManT** [inkle/ink-unity-integration#146]
Hi, I was wondering if this repo could be configured to allow us to add the package via git URL in UPM so there's no need to manually update with each new release? Or if someone could instruct me as to how to add it via git URL in UPM?

**Comment by mikz** [comment]
You can use install it from`https://github.com/inkle/ink-unity-integration.git?path=Packages/Ink`

**Comment by tomkail** [comment]
This is finally addressed! Please see the info in the readme.
