### ISSUE TITLE
No feedback on ink compilation success after failure

### ISSUE THREAD

**Issue by toolness** [inkle/ink-unity-integration#15]
When an ink error occurs, the following kind of message appears in the status bar at the bottom of the Unity editor:

![ink-error](https://cloud.githubusercontent.com/assets/124687/15633621/ecea7d96-257f-11e6-93e4-a30f66b258bc.png)

However, upon fixing the error in an editor and switching back to Unity, this line doesn't go away, which leads me to believe that something is still wrong with the file. It's only by going to the Console window and clicking "Clear" before making changes to the `.ink` script that I can confirm that no errors occurred on compilation, which seems unintuitive and inefficient.

Perhaps a message like "Auto-compilation of *[filename]*.ink successful" should appear whenever compilation succeeds?

Note that this might actually be a bug with Unity itself; I've noticed that a similar kind of problem exists with Unity's built-in [Editor Tests Runner](http://docs.unity3d.com/Manual/testing-editortestsrunner.html). If that's the case, feel free to close this issue!

**Comment by tomkail** [comment]
Yeah, this is an issue. I think printing a final log message on compilation
is a better idea than clearing the whole console. I'll add it to the next
release.
