### ISSUE TITLE
CompileInkThreaded was called on a file that is already compiling

### ISSUE THREAD

**Issue by 1bardesign** [inkle/ink-unity-integration#150]
```
CompileInkThreaded was called on a file that is already compiling! This is most likely a threading bug. Please report this!
UnityEngine.Debug:LogWarning (object)
Ink.UnityIntegration.InkCompiler:CompileInkThreaded (object) (at Assets/Ink/Editor/Core/Compiler/InkCompiler.cs:396)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

Upon re-import on updating to 1.0.0 of a multi-file ink codebase.

**Comment by 1bardesign** [comment]
After rebuilding the library, this warnings continues to be raised sometimes upon recompiling (from the context menu or automatically).

**Comment by tomkail** [comment]
This is believed fixed in recent times. Will leave this open a bit longer and then close if we don't hear any more reports!
