### ISSUE TITLE
Conditional choices are not respected.

### ISSUE THREAD

**Issue by jenmakesgames** [inkle/ink-unity-integration#151]
I've got a choice that needs to show 3 times, and then be removed (so I can't use a * choice). I tried to do this by adding a variable that counts how many times the choice has been selected, and putting that choice in an if-style statement:

```
{-count < 3:

+ [Make a choice]
    -> MakeTheChoice

}
```

But this doesn't work - Unity always shows this choice when I call story.currentChoices, no matter how many times MakeTheChoice is called (the count variable is incremented in the MakeTheChoice knot).

Is there another way I can limit the number of times a choice can be selected?

**Comment by joethephish** [comment]
Try changing `-count` to `count` - looks like you're negating the count, so it's always less than 3?

**Comment by jenmakesgames** [comment]
According to the docs, the `-` just makes it into the general switch like statement. But I tested it anyway and it worked! - Thanks :)

**Comment by joethephish** [comment]
Ah, in this case, the new line is important:

    {-count > 3:
        something
    }

is very different to:

    { // nothing on this line!
    
        - count > 4:
            + lots -> END
        - count > 3:
            + medium -> END
        - else:
            + not that much -> END
    }
