### ISSUE TITLE
No "TryGetExternalFunction" function

### ISSUE THREAD

**Issue by Arcnor** [inkle/ink-unity-integration#160]
Current master doesn't seem to compile because `Story.TryGetExternalFunction` doesn't seem to exist at https://github.com/inkle/ink-unity-integration/blob/b74a1cacb71c75cdd2bb2e4fb80e95c90d4504f7/Packages/Ink/Editor/Tools/Player%20Window/InkPlayerWindow.cs#L2013 . Maybe a slight oversight when pushing something?

**Comment by tomkail** [comment]
Ack! Yes, thanks. Fixed!
