### ISSUE TITLE
Namespace 'Ink' not found

### ISSUE THREAD

**Issue by luiginor27** [inkle/ink-unity-integration#162]
I've just imported the last version but when I try to use the package from my scripts I get
`"The type or namespace name 'Ink' could not be found"`

I don't know if I'm missing a step, but I cannot find a solution to this.

Unity version: 2021.2.6f1

**Comment by tomkail** [comment]
Hi! Did you resolve this? Sounds like it’s failed to compile properly.

**Comment by luiginor27** [comment]
I still have the errors shown on Visual Studio, and I can't autocomplete, but it all works at running time.

**Comment by tomkail** [comment]
Ah right! This sounds like a VS issue. Maybe clear your proj files in the
unity External Tools settings?
