### ISSUE TITLE
Exception: Trying to call EXTERNAL function which has not been bound

### ISSUE THREAD

**Issue by aschearer** [inkle/ink-unity-integration#164]
Just downloaded the latest off github and I get constant errors: `Trying to call EXTERNAL function 'raiseEvent' which has not been bound (and ink fallbacks disabled).`  when viewing a story in the `Ink Player` -- disabling `Auto-Continue` seems to fix it.

**Comment by tomkail** [comment]
Hmm a search for "raiseEvent" turns up nothing at all for me. Do you have
an external function called that in your ink, and are you tethering your
story to the ink player window on start?

**Comment by Profakos** [comment]
I have the same issue. The exception displays my external function that is the first defined in the ink file, despite fallback functions existing, and likewise, disabling Auto-continue solves the issue when playing an ink file outside of play mode.

**Comment by tomkail** [comment]
Can someone share an example ink file so I can debug this please?

**Comment by Profakos** [comment]
I will prepare a sample file later today.

**Comment by tomkail** [comment]
Thank you! I've fixed this on latest.

**Comment by aschearer** [comment]
Y'all are the best!

**Comment by Profakos** [comment]
Thank you for the fix! :)
