### ISSUE TITLE
Compile Error With Ink

### ISSUE THREAD

**Issue by Ymit24** [inkle/ink-unity-integration#17]
"Compiler bug prevented compilation of JSON file" i imported ink into empty unity 5.3.5 project and created new ink file by the right click->create->Ink menu. and it is using the template ink, but when i press compile in custom inspector it opens inklecate window and then says it has stopped responding and gives the error this comment started with. please someone help me fix this error becuase i would love to use ink to make cool games.

- Ymit

**Comment by facelesspanda** [comment]
there is currently an internal depedency problem between ink-engine.dll, inklecate executable, and Newtonsoft.Json.dll.

To workaround this you could grab the ink repo from [/inkle/ink](https://github.com/inkle/ink), open the .sln solution with visual studio, build the whole thing (following the instruction on the readme file over there), and then place the resulting inklecate executable and engine dll file in separate folders, each with their own version of the newtonsoft dll, in your Unity project.
If you did not understand that, please don't try anything, it simply means it's out of your abilities and you could end up in a bigger mess than you were before.

That's what I did, but I really don't like having twice the same file (newtonsoft.json.dll) in my architecture. It's an issue they are aware of and are currently investigating.

Point is, it's not your wrong doing, there's simply a bug in the released plugin, waiting to be fixed.

**Comment by tomkail** [comment]
Hum, thanks for the bug report! Have you tried an older version? Some
updates in the latest have been causing problems for some users - we're
working on it!

**Comment by joethephish** [comment]
This should be fixed in the [latest version](https://github.com/inkle/ink/releases/latest) where we've removed our dependency on Newtonsoft.Json.dll. But let us know if you still have any problems!
