### ISSUE TITLE
Are regular Ink functions (not external) available via the Unity Integration?

### ISSUE THREAD

**Issue by Bard09** [inkle/ink-unity-integration#171]
Is it possible to reference regular (not external) functions in Unity/C#?  The "Running Your Ink" documentation doesn't mention anything about regular Ink functions, and in my testing, function names don't appear accessible via variablesState.

If no-- 

1. Is this planned?
2. What is the best practice solution for this need currently?  Populate it in Ink into a standard variable?  Move the calculation to an External Function?

**Comment by joningold** [comment]
story.EvaluationFunction("ink_function_name", parameters as required)

**Comment by Bard09** [comment]
I'm so relieved that it's already implemented!  Thank you @joningold.  Was there a documentation resource on this I missed?

**Comment by tomkail** [comment]
Looks like it's not in the docs! I'll add that now. I've been wanting to add proper demos to this repo for the longest time to cover all the core functionality.
