### ISSUE TITLE
Unity only recompiling first root file when nested includes are edited 

### ISSUE THREAD

**Issue by ecoludology** [inkle/ink-unity-integration#175]
Root1.ink and Root2.ink both include Include.ink, which in turn includes IncludeOfInclude.ink
Editing Root1 or Root2 causes that file to be recompiled upon returning to unity, as expected.
Editing Include causes both Root1 and Root2 to be recompiled, as expected.
BUT editing IncludeOfInclude causes only Root1, not Root2, to be recompiled.

[BugReport.zip](https://github.com/inkle/ink-unity-integration/files/10163362/BugReport.zip)

(Our actual use case is that we have a bunch of scenes as separate ink files, all of which include a common.ink, which itself includes a 
bunch of configuration files - editing one of these nested config files doesn't properly trigger the recompilation of all of the scene files)

**Comment by tomkail** [comment]
Hey! Thanks, this is a nicely formatted report :D
I've done a complete re-write of the way the plugin connects files via includes that fixes this in the development branch. I'll merge it once you've gotten back if you're happy!
