### ISSUE TITLE
Unity saying "UnityIntegration" does not exist in the namespace "Ink"

### ISSUE THREAD

**Issue by ElijahShaver** [inkle/ink-unity-integration#176]
So, for context, I'm making an RPG game using Unity, and found out that Ink is a great tool for the dialogue. Development has went smoothly, and up until now, I had no issues with it. UnityIntegration worked great in both Visual Studio and in Unity. Every time I playtested my game in the editor, no exceptions occurred regarding it. However, when I actually began to make a build of the game, disaster struck. For anyone curious, I used this tutorial to store a global ink file with variables: https://youtu.be/fA79neqH21s

I have no idea why this is happening. I do have a backup idea planned in case I can't find a fix, but I'm asking just in case there is one. Thanks in advance!
![issue](https://user-images.githubusercontent.com/89484052/207983202-11f085ed-ee85-479c-af00-a674ac908d3b.png)
![issue2](https://user-images.githubusercontent.com/89484052/207983209-c12bacdc-3000-45b7-80c7-61b7d5479f45.png)

**Comment by tomkail** [comment]
Hey! InkFile.cs is an editor script, so you can’t build with references to
it. You probably need to wrap some of your code in #IF UNITY_EDITOR tags.

**Comment by ElijahShaver** [comment]
Ah ok, that makes sense. Thanks for telling me! I'll see if I can find out how to do that :)
