### ISSUE TITLE
null path and null currentPointer during the first line of a knot

### ISSUE THREAD

**Issue by molleindustria** [inkle/ink-unity-integration#189]
Hello everybody! Thank you so much for Ink (and inky). It's the best game making tool I've ever used and I'm building a big project around it. 
I've been banging my head against this bug or limitation. I don't know if it's due to ink or its Unity integration.

In some cases, after a story.continue() the path and the currentPointer are null, and there is no way to know where you are in the story, even if the story works fine. 

Here's an example with nothing but debugging messages added to the Basic Demo. 
If you divert to a knot or a stitch made by a single line, the path is always null. 
If the knot is two lines, then the first line will have a path right after the continue. 
If the pointer is retrieved before the continue, it will be the id of the choice. Basically there is no state in which I get "c1" as pointer name or path.
I understand that the path can be undefined if there are [injections](https://github.com/inkle/ink-unity-integration/issues/38#issuecomment-326230174) but this doesn't seem to be the case.
It obviously knows where it is, but I guess something in the stack order overwrites the path before I can read it or waits to write it until the second line.
Is there any workaround, any way to retrieve it? 

![nullpath ink](https://github.com/inkle/ink-unity-integration/assets/12369651/017a876b-0512-459a-8eb3-86b0ff8e1c21)

**Comment by tomkail** [comment]
Hi! I’m afraid paths don’t work in the way you might hope; they also don’t
get set immediately on loading a save state. This is more of an issue with
ink than the Unity plugin. That said, I actually made a branch to try to
fix this a while ago - check out “currentContainerPathString”. I can’t
recall how robust it was but it seemed to work last I checked. You can also
see the current path in the Ink Player Window when using it, handy for
debugging.

**Comment by tomkail** [comment]
I see! There’s lots of ways of solving that problem. Paths aren’t
recommended because they don’t work like that without the patch in the
branch.
The solution of just telling unity in some way is pretty standard, but if
you have a huge number of locations I can see how it might get annoying!
