### ISSUE TITLE
Newest version of ink not available in Unity's asset store

### ISSUE THREAD

**Issue by Kindleguy** [inkle/ink-unity-integration#19]
I just want you to know that the newest version of ink is not available in Unity's asset store. I see that the current version is now 0.4.0. The version available in Unity's asset store is right now 0.3.51, which I downloaded first and experienced a compile error like this one: https://github.com/inkle/ink-unity-integration/issues/16

Luckily, I figured out on that forum thread that a new, working version of ink was available here (0.4.0): https://github.com/inkle/ink/releases/tag/0.4.0

It would be nice if you could upload newest version to Unity's asset store, so that other newcomers (in Unity) do not get scared away from using ink due to compile error.

**Comment by tomkail** [comment]
It's been submitted, we're just waiting on unity to approve it
