### ISSUE TITLE
How to transfer variable values from one Ink story to another Ink story?

### ISSUE THREAD

**Issue by bigpng** [inkle/ink-unity-integration#194]
I have the following variable at globals.ink:
````
VAR affinity = ""
````
And the following in Scene1.ink:
````
~ affinity = "Shenzhen"
````
I want to pass `affinity` to Scene2.ink but I only get the variable value from globals.ink. I have tried to set value and get value through External functions, and tried to play with ObserveVariable. Nothing seems to work. And I cannot find any documentation on how to pass values to a different Ink story. I would appreciate any help.

**Comment by tomkail** [comment]
Not sure I follow? If scene 1 and 2 are part of the same story then you
don’t need to do anything. If they’re separate stories then you’ll need to
copy the value over like you say - I can’t see why setting the variable
wouldn’t work. For debugging I recommend using the Ink Player Window in
Unity.
Can you re-explain?
