### ISSUE TITLE
How does the include system work?

### ISSUE THREAD

**Issue by wilg** [inkle/ink-unity-integration#195]
The include system is not documented, so I am having trouble figuring out why the include system changes in https://github.com/inkle/ink-unity-integration/commit/89af8014635c00fffd7c5c569a788328d383b6c8 broke compiling Ink for me.

It seems that it now thinks all my included files are master files, and fails to compile them as such because they don't have functions and knots etc defined. Why might this be happening?

**Comment by wilg** [comment]
Unchecking "Compile all ink automatically" in settings does not work, because then a change to a file that is included in my story file does not cause the story to recompile.

**Comment by wilg** [comment]
Oh, I randomly chose "Rebuild Ink Library" and it fixed itself. I'm not sure what the Ink Library is or why I had to rebuild it, but it worked.

**Comment by tomkail** [comment]
The InkLibrary is the part of the integration plugin that tracks ink files
and their relationships to each other. So. Your fix was the correct one!
I’d not realised that upgrade would affect libraries - let me know if it
happens again!
