### ISSUE TITLE
Unity 2022.3.7f1 issues: demo scenes do not open, reload doesnt work.

### ISSUE THREAD

**Issue by SamTyurenkov** [inkle/ink-unity-integration#196]
Hi, I'm first time ever Ink user, maybe Im doing something wrong: 

I downloaded unity ink integration via unity package manager, downloaded inkly for editing.

I had some javascript crash in inkly, and probably after that (or maybe its unrelated) in unity ink doesnt reload/restart json, doesnt open demo scene and maybe doesnt work in some other ways as well:

![image](https://github.com/inkle/ink-unity-integration/assets/19373777/abc83448-eb48-43b3-b62e-3222c36f32c9)

and this is shown when trying to reload json

![image](https://github.com/inkle/ink-unity-integration/assets/19373777/8cefb050-b35d-4a85-8e1a-bed9c755e97b)

here is the ink file that doesnt reload:

```
Start before knot
* This is a choice that can only be chosen once
-> start_dialog

=== start_dialog ===
Started Dialog.
* Choice one 1
-> finish_dialog
* Choice two
-> finish_dialog
-> END

=== finish_dialog ===
Finished dialog.
-> END
```

**Comment by tomkail** [comment]
Oh thanks for the report! The pptr error is normally because the scene is
from an older Unity version or something. It normally goes away after a
save. Bit annoying but I doubt that’s the issue here.
The one about the editor window I’m less sure of. I’ll have a look. In any
case a restart of unity should fix it? Let me know in any case!

**Comment by SamTyurenkov** [comment]
After Unity restart Im able to open the demo scene and it works, I suppose json reload doesnt work cause my ink syntax isnt correct then?

**Comment by tomkail** [comment]
Most likely yeah - it should recompile ink automatically. Are there errors
in the console? Or inky?
