### ISSUE TITLE
Why isn't the parent ink file attached to the data of the knot?

### ISSUE THREAD

**Issue by Necronomison** [inkle/ink-unity-integration#202]
Context:

We've broken up the structure of our ink story so that there is one ink file that includes a handful of other ink files which each represent a chapter in our game.

However, I've just noticed that when the ink unity integration compiles the file into a json, there's nowhere in the json data to track which knot belongs to which (sub) ink file so that I can figure out what chapter that knot belongs to.

Is my only option to rename all knots so that their corresponding chapter is included in the name? This isn't ideal as it solutes the already descriptive knot names. Is there another way to achieve what I'm trying to do?

Any help would be greatly appreciated.

**Comment by tomkail** [comment]
Hey! Yeah I’m afraid you can’t do what you’re after - included ink files
are really just for organisation - they’re essentially turned into a single
file for compilation. You could consider: use stitches inside knots, set a
variable when you enter your knot, or build a database pattern. Try the
discord too, I’m sure there’s people on there with other ideas!

**Comment by WolvenBard** [comment]
Oh I guess one problem would be that compilation would fail on any of the include files if they reference variables from other files :(

**Comment by tomkail** [comment]
Hmm I’ve never done that and it sounds hacky, but hey maybe it’ll work?
Database pattern:
https://www.patreon.com/posts/tips-and-tricks-18667641
Path references are variables so you can basically build a dictionary that
maps knots to arbitrary data
