### ISSUE TITLE
`Todo` in InkCompiler.cs

### ISSUE THREAD

**Issue by facelesspanda** [inkle/ink-unity-integration#21]
Hello.

I was looking up my Visual Studio Task window and I saw this:

Priority | Description | File | Line
---------|--------------|-----|------
Normal | Todo - switch this to pendingFile.inkFile.includesInkFiles | InkCompiler.cs |	225

Is this something we user have to ignore, or should we care about it?
It's present in the 0.4.0 unitypackage release over at inkle/ink.

EDIT:
I found it in the file in this repo, actually line 228.

**Comment by tomkail** [comment]
Something to ignore - we'll tidy up for the next release

**Comment by facelesspanda** [comment]
Okay thanks.
