### ISSUE TITLE
AssetDatabase doesn't work with StreamingAssets

### ISSUE THREAD

**Issue by DMinsky** [inkle/ink-unity-integration#23]
Right now Unity Inspector can't show "Play" button on compiled Ink file if Ink file located in StreamingAssets folder. 

[`Screenshot`](http://i.imgur.com/9n6WMAW.png)

Just because AssetDatabase doesn't work with StreamingAssets folder. To fix this behaviour you can replace AssetDatabase.LoadAssetAtPath with File.ReadAllText to fill inkFile.jsonAsset Also, for this you need to change jsonAsset type from TextAsset to string (maybe?)

**Comment by tomkail** [comment]
Interesting! I admit I've never used StreamingAssets myself so it's never
come up! Unless you'd like to have a go fixing it yourself I'll take a look
in the coming week.

**Comment by tomkail** [comment]
Fixed!
