### ISSUE TITLE
Line number

### ISSUE THREAD

**Issue by romeo131** [inkle/ink-unity-integration#31]
Hello guys, 

Is there any way we can track the line number in Unity? We need to track the line number when the player out of the story but we don't know how we can matching the line number and the actual story.

Thanks!!!

**Comment by joethephish** [comment]
Sorry, not right now! It's planned but requires implementing a source map feature which isn't trivial. I hope to print a stack trace of sorts as a stop gap feature until we get line numbers working though, which will give you the name of the knot / stitch at least.

**Comment by romeo131** [comment]
I see. Thanks to confirm that!
