### ISSUE TITLE
Question on selecting choices by NPC

### ISSUE THREAD

**Issue by pejmansajjadi** [inkle/ink-unity-integration#36]
Hello, 
I have recently started to use Ink, and I am very excited about its amazing capabilities. I am trying to do something rather simple, but I am not sure what would be the best way for doing it. I would like to have a simple dialogue system between the player and an NPC, however I need the NPC to have multiple options to choose from (automatically) based on the state of the player. Is there a way for guide the decision making of the NPC within Ink? or perhaps, adding some script in unity that will reason over the possible options the NPC can select from, and then choosing the most appropriate is a better direction to go? 
I would appreciate you help, and my compliments on this amazing work.

**Comment by facelesspanda** [comment]
What's sure is the AI has to be on your game side (Ink's logic is fine enough for state-logging, but not actual AI), so what you need is
* a way for the game to know there are options to choose from
* a way for the game to know what the options are and what they "mean"
* a way for the game to choose the option.

You could have a line in the ink code saying "okay, these choices are for this character", like with tags and stuff.
```
* some player choice
  # npc Mark
  * * Mark's first option
  * * Mark's other option
```
In your story loop in your game, you then look for the tags "npc", get the name, and then relay the choices to your AI NPC agent.
But here, I have nothing but text to convey, and it would take a lot of logic power to process this text.
So I'd add some tags in there to indicate what these choices would do.
```
# npc Bob
* * blah blah # aggressive
* * blah bluh # friendly
```
you can go with a word-based list of "emotions" like `aggressive` or `sarcastic`,
or go the numeric route and have a number-based code for your options.
It's up to how you want your AI to work.

Then you have the story loop make the choice with the regular API.

That's if you want an AI.
What you could also do is have variables for each NPC keeping their "personality stats", and have your NPC decisions be computed with `if` statements like `if mark_sarcastic is over 9000 then -> sass_answer` (not ink syntax)
The downside to this is, it's way harder to test and fine-tune your NPC's behavior.

**Comment by joningold** [comment]
I don't mean to disagree really, but we've successfully written a
poker-playing AI in ink previously (in 80 Days; it also shuffles and deals
the pack and describes hands and so forth ) - you can get pretty far with
functions and lists and the like! But you probably *shouldn't* since it's a
lot easier to debug game side code!

Jon

**Comment by facelesspanda** [comment]
I edited my answer to better convey what I meant; debugging was indeed my biggest concern.
