### ISSUE TITLE
[Question] Is it possible to load external ink/json file once unity game is builded?

### ISSUE THREAD

**Issue by sardinax** [inkle/ink-unity-integration#37]
I'd like to edit ink file once unity game is builded to make changes on writer side (and view it re-executing game or pushing some button to refresh ink story). It'd be useful for the writer not to have to install unity.

I've readed InkComplier and InkLibrary but it's a bit complicated to understand easily for me. I think that could work adding new (external) InkFile to InkLibrary.

If this is possible, Can you advise me on the next steps?

Maybe I'm losing something...

Thank you in advance and for your work

**Comment by joethephish** [comment]
Unfortunately this isn't easy. Although the ink compiler is written in C#, it uses newer features that aren't available within Unity, so can't be included in a game that's running. What we do for the editor tools is wrap a pre-built binary version of the compiler and run it on the command line in the background. Theoretically you could bundle the compiler with your game and do the same. But as I said, it's not a straightforward approach I'm afraid!

**Comment by sardinax** [comment]
I think that scares me too :)

I'll translate the game functions to ink editor so that the writer can edit without using unity. I think it's easier.

Thank you

**Comment by joethephish** [comment]
Yup, that's definitely our preferred approach!
