### ISSUE TITLE
Ink compile bug

### ISSUE THREAD

**Issue by snarlynarwhal** [inkle/ink-unity-integration#39]
I found a bug in InkMetaFile.cs that occurs in the FindIncludeFiles method upon compilation when using this folder/include structure:
```
Main.ink // INCLUDE Chapter/Chapter.ink (includes main import for each chapter)
Chapter/Chapter.ink // INCLUDE Chapter/Chapter_1.ink (includes multiple parts of chapter 1)
Chapter/Chapter_1.ink // ink content for Chapter 1
```
The compiler locates `Chapter/Chapter.ink` just fine, but when it goes locate `Chapter/Chapter_1.ink` it freaks out because it looks for them relative to their parent `Chapter/Chapter.ink ` instead of the master ink asset `Main.ink`. 

Aka it looks for `Chapter/Chapter/Chapter_1.ink` instead of `Chapter/Chapter_1.ink`.

I'm not sure if this is the most appropriate fix, but I replaced the first line in the InkMetaFile.FindIncludeFiles method:

Replaced:
```
string localIncludePath = InkEditorUtils.CombinePaths(Path.GetDirectoryName(inkFile.filePath), includePath);
```
With:
```
string localIncludePath = masterInkAssetPath == "" ?
					Path.GetDirectoryName(inkAssetPath)+"/"+includePath :
					Path.GetDirectoryName(masterInkAssetPath)+"/"+includePath;
```
And that seems to work just fine.

UPDATE:
The error appears to be a false positive. It seems to compile with the original line of code, but it does throw errors.

**Comment by tomkail** [comment]
Thanks for the report - looks like we never nest includes so it's never come up. If you've got a robust fix we can merge it in, else I'll take a look next time we do a release.

**Comment by snarlynarwhal** [comment]
In case you missed my update:

> The error appears to be a false positive. It seems to compile with the original line of code, but it does throw errors.

So might just need to fine-tune the error handling for that code. I've just been ignoring it haha.

Not sure if this would be a proper fix, but:

```
string localIncludePath = masterInkAssetPath == "" ?
					Path.GetDirectoryName(inkAssetPath)+"/"+includePath :
					Path.GetDirectoryName(masterInkAssetPath)+"/"+includePath;
```

did seem to compile it without errors.. so maybe give that a look next release. Thanks!

**Comment by artyomt** [comment]
Hi! There is another problem with includes from parent directory.
Ink files hierarchy:
> Assets/Stories/misc.ink
> Assets/Stories/Story1/story.ink

story.ink includes misc.ink:
> INCLUDE ../misc.ink

But I have an error at Ink compile
> Assets/Stories/Story1/story.ink expected child Ink file at Assets/Stories/Story1/../misc.ink but file was not found.
and Ink file inspector doesn't show included file.

It seems like LoadAssetAtPath doesn't understand relative paths (https://github.com/inkle/ink-unity-integration/blob/master/Assets/Plugins/Ink/Editor/Ink%20Library/InkMetaFile.cs#L209). 
We do it by hands right now, so it looks like that
```
var regex = new Regex("[^\\/]+\\/\\.\\.\\/");
while (regex.IsMatch(localIncludePath))
{
	localIncludePath = regex.Replace(localIncludePath, "");
}
```
And that solve that problem.

**Comment by tomkail** [comment]
Right ok - so that seems to fix the issue, but we think the official solution here is to instead convert the localIncludePath to an absolute path, clean it with Path.GetFullPath, and revert it to a relative path. Should be a bit faster. We'll include it in the next update!

**Comment by artyomt** [comment]
Yes, it will be great. Thank you

**Comment by HashBuoy** [comment]
Still facing this issue, not able to load common files in another parent directory.
`INCLUDE ../Common/ink_helper.ink`

Error : Ink Error: Failed to load: '../Common/ink_helper.ink' (at tutorial_story.ink:1)

**Comment by HashBuoy** [comment]
Still facing this issue in the ink windows editor. Compiles properly in unity, only in the ink editor, fails to load the file.

**Comment by tomkail** [comment]
If you mean this works in unity, please take this bug to the inky repo
instead :)
Am I misunderstanding something?

**Comment by HashBuoy** [comment]
Opps my bad :)
