### ISSUE TITLE
Changes in Ink not reflected in Unity

### ISSUE THREAD

**Issue by AdamNashGames** [inkle/ink-unity-integration#41]
When I make changes to my INK file and return to Unity, it compiles successfully, and then the inspector even shows my changes reflected fine when I select the ink file asset.  However, when I play the game, none of the changes are reflected!  It's simply as though I never made the edits.

Tested this on 3 Macs running OSX and this happened.  However, tested it on a PC and it worked fine!

Further, when I did an SVN Commit from the PC and Update from the Mac, it DID work!

Any idea what might be getting stuck when I try to edit the INK file from the Mac?

**Comment by tomkail** [comment]
Weird! Can you clarify if it's the ink file not keeping its changes, or the compiled json file? Also I doubt this is the case but I would check if the json file running in the game is the one that's being compiled! Also - what editor are you using for ink?

**Comment by AdamNashGames** [comment]
Thanks so much for the speedy reply!  I'm using Sublime Text 3 as text editor for .ink files.  

The changes are definitely being saved in the file; when I open the file again in Sublime, my changes are intact.  In Unity, when I highlight the asset, the inspector preview does show the changes.  And it even acknowledges that changes were made by automatically compiling the ink files.  

I made a change to something near the top of the file so I could find it in the JSON's inspector preview, and I confirmed that indeed it is NOT updating with the changes.  

Trying Rebuild Ink Library and Recompile All Ink didn't seem to work. 

Thanks!

**Comment by tomkail** [comment]
Right, so it's compiling but the compiled file doesn't appear to change?
That the file isn't updating in unity after changing it manually suggests
to me that unity isn't registering any changes so doesn't reimport the
asset. Can you try reimporting the json, or else deleting it and
recompiling the ink?

**Comment by AdamNashGames** [comment]
Reimporting seems to do nothing.  When I delete the JSON and go to compile the INK again, the console makes it look like it compiled with an "Ink Compilation Completed" log.  But it generates no new json.  The ink's inspector's json slot says None and it shows the the "Ink file has not been compiled".  In fact, now I can't figure out how to get it to generate a new json at all ( but no worries, our project is backed up on svn :) )

**Comment by joethephish** [comment]
It’s far from optimal, but if you really need to get up and running again, you can use inky (or indeed the command line compiler if you like) to export your json manually. And that would be a good test to see if there’s some kind of odd error that the ink unity integration package isn’t catching for some reason.

**Comment by AdamNashGames** [comment]
I exported json from Inky and imported to Unity, but I think I'm missing a step.  I'm not able to assign the file to the ink's text asset slot.

**Comment by joethephish** [comment]
Hmm not sure what allows it to recognise a .json file as a text file. If you change the extension to .txt does it work?

**Comment by AdamNashGames** [comment]
So, changing it to .txt did not work, but then I changed it back to .json and deleted the existing corresponding .meta files for both the .ink and .json, and when I returned to Unity, it compiled the changes and recognized and auto-assigned the json asset, complete with my new changes!  

However, now it seems I'm back where I started.  Further changes to the .ink in Sublime are not recognized when it compiles.  The .ink inspector shows the Last edit date as correct (a minute ago), but the Last Compile Date as several minutes ago - from when I deleted, changed extensions, etc. 

So at this point, I'm able to get my changes recognized with the following steps:
- Delete the json and all the .meta files associated.  (I have been deleting all .meta files associated with INCLUDED files as well, fwiw).  
- Open the .ink in Inky.  
- Export JSON into the Unity project
- Auto-compiles, generates JSON, changes are recognized, all is great.  

And note that when I do these steps without deleting the .meta files, I get this warning when compiling: "'Assets/[MyDirectory]/[MyInkFile].json' does not exist", where [] are my dir/file names.

**Comment by AdamNashGames** [comment]
Hate to "bump", but wondering if there's anything we can do about this? The workaround described above is ultimately fine enough to keep going, but a few of our writers are on Macs and not the most technically savvy people.

**Comment by joethephish** [comment]
Sorry afraid not! Are you on Unity 2017.x by the way? Someone else contacted us over email with a similar issue. We are still on 5.x at inkle so I’m wondering whether it’s related to that. If so it’s unlikely we’ll be able to (have the time to) do anything about it until we upgrade ourselves I’m afraid :-/

**Comment by AdamNashGames** [comment]
We're actually on 5.6.3f1.  No worries, it's not preventing us from shipping with Ink, just an inconvenience.  Thanks!

**Comment by joethephish** [comment]
Oh ok, good to know! That's what we're on too. Though that makes it even more surprising that you're having issues :-/

**Comment by tomkail** [comment]
I’d quite like to get to the bottom of this, and I’m not sure I follow the
exact issue - if you’ve got a few minutes we could skype and I’ll try to
get to the bottom of it?

**Comment by AdamNashGames** [comment]
Hi Tomkail, sorry I've been out of town all week.  I'd be happy to skype tomorrow some time after 1pm EST.

**Comment by tomkail** [comment]
Sounds great, I’ll be free by 2 - I’m tomkail on Skype too.

**Comment by shiftz2run** [comment]
Hi, I've  also encountered this problem, but only when I import the ink plugin from the unity store. The scene I've downloaded from github updates normally. So I'm guessing the compiler file in the unity asset store version might be not updating the json file properly

**Comment by tomkail** [comment]
Thanks for the catch! I've just updated the asset store version so hopefully it'll resolve when it's approved.

**Comment by tomkail** [comment]
Hey, any updates on this? We've got a unity store update coming soon, but this version should be up to scratch.

**Comment by Buvude** [comment]
I figured out how to fix this issue myself. Sorry for bumping/necroing this yet again, however, there is a little check box you can click that says "Should also be master file" That fixed it for me. This may cause other issues for files that are simply referred to through ink, and not called through unity, but this works for my issue. The comment towards the begening about the json file not updating was a huge help to finding this. 
![image](https://github.com/inkle/ink-unity-integration/assets/90856761/345cc820-291c-491d-ab36-2629d99c3f09)
