### ISSUE TITLE
Compilation Error when Dropping Multiple Ink files with INCLUDEs Into Unity

### ISSUE THREAD

**Issue by Horatio-Blackwood** [inkle/ink-unity-integration#5]
**OS** - Windows 7 64bit
**ink-unity-integration version:**  0.33

If I drop these three files into an ink/unity project by copying and pasting them from another directory compilation completes but the ink script fails to run in the ink player.

** Steps to reproduce**
1. Make sure any output Copy and paste the three .ink files into the ink directory in the assets dir of a ink/unity project.
2. Observe that the compilation cmd windows pop up and go away - no crashes.  No errors appear in the Console output.
3. Observe that two .json files are generated:  main.json and state.json.
4. Select the main.ink file and click the play button in the unity inspector window.
5. Observe the following error appears in the console.

When I select 'main' and try to run the ink script, I get this error in the console:
NullReferenceException: Object reference not set to an instance of an object
Ink.UnityIntegration.InkPlayerWindow.Play (UnityEngine.TextAsset storyJSONTextAsset) (at Assets/Plugins/Ink/Editor/Player Window/InkPlayerWindow.cs:87)
Ink.UnityIntegration.InkPlayerWindow.LoadAndPlay (UnityEngine.TextAsset storyJSONTextAsset) (at Assets/Plugins/Ink/Editor/Player Window/InkPlayerWindow.cs:70)
Ink.UnityIntegration.InkInspector.OnInspectorGUI () (at Assets/Plugins/Ink/Editor/Ink Inspector/Ink Inspector/InkInspector.cs:106)
Ink.UnityIntegration.ObjectEditor.OnInspectorGUI () (at Assets/Plugins/Ink/Editor/Ink Inspector/Ink Inspector/ObjectEditor.cs:31)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1231)
UnityEditor.DockArea:OnGUI()

[state.txt](https://github.com/inkle/ink-unity-integration/files/248266/state.txt)
[main.txt](https://github.com/inkle/ink-unity-integration/files/248264/main.txt)
[some_ink_file.txt](https://github.com/inkle/ink-unity-integration/files/248265/some_ink_file.txt)

**Comment by tomkail** [comment]
Let me know if you're still getting this!

**Comment by joethephish** [comment]
(Hotfix package available here: https://github.com/inkle/ink/releases/download/0.3.4/UnityInkIntegration0.3.4_Hotfix_2.unitypackage - hopefully fixes both of your issues!)

**Comment by Horatio-Blackwood** [comment]
Tom / Joe,

I'll check this out as soon as I've got a spare moment.  Thanks for taking a look.  Obviously, you think you have a fix for these issues if you've issued a hotfix.

I see a couple of change sets indicating some more / vs \ nonsense, *shakes fist towards Microsoft HQ* were those the potential source of the problem?  Or is there more than that involved?

Thanks!

- HB

**Comment by tomkail** [comment]
It's possible! We're mac people, so it's a bit hard to tell - I *think* that's the last of those bugs, we've not had any more reports this evening.
Let us know how you get on!

**Comment by Horatio-Blackwood** [comment]
I'll certainly let you all know.  I'm wondering if InkFile.cs should just have a 'sanitizeSlashes(string path)' method that it calls when any of its paths are modified or set so that callers of that class could just use whatever paths they have been given and InkFile.cs would take care of the rest.

It seems like we're sprinkling that string replace line EVERYWHERE, and honestly, it only needs to be in a single place to protect the internal state of that object.  If we did that, I think we could kill the \ replace usage in InkLibrary, as it would always return properly formatted paths.

Anyways, just a few musings.  Thanks, I'll let you know what I find out.

**Comment by tomkail** [comment]
Yeah, that's a really good idea - it's starting to get a bit messy. Because I can't easily test it I'm a little wary to do this myself right now, but if you fancy it, free to create pull request and I'll bring it in for the next release!

**Comment by Horatio-Blackwood** [comment]
Yeah, without a windows test station you're probably not as able to verify that its working here or there.  Once I re-familiarize myself with the latest changes, I may take a crack at it.  Thanks Tom!

**Comment by Horatio-Blackwood** [comment]
Closing as this issue is resolved by ink-unity-integration v0.3.4, Hotfix 2.

Thanks!
