### ISSUE TITLE
Error compiling inks on Unity plugin, using Unity 2017.03.0f3

### ISSUE THREAD

**Issue by walaber** [inkle/ink-unity-integration#50]
Hello, I downloaded the Unity integration from the asset store, and tried to compile my first .ink file, and got the following error:

Unhandled error(s) occurred compiling Ink file 'Assets/Plugins/Ink/Example/Ink/story.ink'! Please report following error(s) as a bug:
﻿

UnityEngine.Debug:LogError(Object)
Ink.UnityIntegration.InkCompiler:Delay() (at Assets/Plugins/Ink/Editor/Compiler/InkCompiler.cs:245)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()

I tried downloading the latest unity package release from your site as well (0.7.4), but I'm getting the same error.  If I try to recompile the example .ink (Ink/Example/Ink/story.ink) I get the same error, so I don't think it's a syntax error or other issue specific to my ink.

**Comment by tomkail** [comment]
Hey, thanks for the heads up. We’re on unity 5.6 and it seems to work fine
- can you tell us which OS you’re on?

**Comment by walaber** [comment]
I'm on OSX 10.13.2
Interestingly, after I used a temporary workaround of installing Inkle and exporting the JSON from there, the compiling inside Unity is now working without error.  Not sure what I did other than install Inkly, and also restart Monodevelop once.

**Comment by tomkail** [comment]
I'm debugging now. Its actually compiling correctly, but finding errors so it doesnt refresh unity's project window and show the newly created file. Fix incoming in <30 mins, but for now just ignore the error.
