### ISSUE TITLE
Detecting if stitch/knot has been visited before

### ISSUE THREAD

**Issue by Azurelol** [inkle/ink-unity-integration#52]
Hello,

My team is currently implementing a fastforward/skip feature for when dialog has been read before dynamically but haven't found an easy way in the current Ink API to do so; There's VisitCountatPathString which works if I know the knot ahead of time, but since we have many story files with many knots the approach is unsustainable.

We would very much appreciate a way to know on what stitch/knot we are currently on every line read. At least that way we could perhaps query the visit counts? Right now our approach is the following:

![image](https://user-images.githubusercontent.com/10147802/35838581-d007ee7c-0aa0-11e8-8da3-425c7a0019e8.png)

It obviously... doesn't make me very happy. Is there a better way?

**Comment by joethephish** [comment]
Hmm, no, that's probably your best bet to be honest! That approach should work, though bear in mind that you could be repeating content at a more granular level within the current knot. But if that doesn't matter to you, it should work!

**Comment by joningold** [comment]
I would approach this in the ink script itself:

=== dialogue_knot
Jim:   Take us to warp factor ten!
{once:
-  Scotty: I cannae do that Captain!
   Jim:   Yes you can!
   Scotty: All right, then!
}
-> next_bit
