### ISSUE TITLE
spaces in project names break compiler

### ISSUE THREAD

**Issue by csrhodes** [inkle/ink-unity-integration#55]
Sorry about this: this bug report is a bit of a guess.  In the workshop I'm currently in, the blank ink file doesn't compile I think because there is a space in my project name.  My project is called "Ink-Unity Workshop" in `/home/christophe`, and the error message is `Cannot open assembly '/home/christophe/Ink-Unity': no such file or directory`.

**Comment by tomkail** [comment]
ah we've definotely heard of spaces causing issues. What file and line of
code was the error coming from? It'll show you if you click the error
message.

On Sat, Feb 17, 2018 at 2:49 PM, Christophe Rhodes <notifications@github.com

**Comment by tomkail** [comment]
My test project now uses spaces. No issues.
