### ISSUE TITLE
BasicInkExample text.Trim() use is erroneous

### ISSUE THREAD

**Issue by KumoKairo** [inkle/ink-unity-integration#58]
https://github.com/inkle/ink-unity-integration/blob/master/Assets/Plugins/Ink/Example/Scripts/BasicInkExample.cs#L33

`Trim()` method returns a new augmented string, it doesn't change the string itself
https://msdn.microsoft.com/en-us/library/system.string.trim(v=vs.110).aspx

It's a minor issue, but better fix it so it doesn't misguide new users

I will create a pull request

**Comment by tomkail** [comment]
Oh good spot. Thanks!
