### ISSUE TITLE
Infinite Ink Compilation Errors on Unity Startup with version 0.3.4

### ISSUE THREAD

**Issue by Horatio-Blackwood** [inkle/ink-unity-integration#6]
**OS** - Windows 7 64bit
**ink-unity-integration version:**  0.34

When Unity is started with the attached ink files in my assets directory the auto-compile function of the plugin kicks off and results in infinite inklecate compilation errors in the console.  In order to stop them, it is necessary to kill Unity.

Its very possible this bug is related to issue #5 , but is manifesting itself differently with the new version of the plugin.

Steps to Reproduce:

1 - Create a project with the new ink-unity plugin in Unity, then close the Unity editor.
2 - Create the following directory ~<project name>/Assets/Plugins/Ink/story
3 - Drop in the attached files.
4 - Start Unity and open the project.
5 - Errors begin to appear in the console, it eventually reports "999+" with the following Stack Trace:

NullReferenceException: Object reference not set to an instance of an object
Ink.UnityIntegration.InkInspector.<CreateIncludeList>m__1 (Rect rect, Int32 index, Boolean isActive, Boolean isFocused) (at Assets/Plugins/Ink/Editor/Ink Inspector/Ink Inspector/InkInspector.cs:67)
UnityEditorInternal.ReorderableList.DoListElements (Rect listRect) (at C:/buildslave/unity/build/Editor/Mono/GUI/ReorderableList.cs:547)
UnityEditorInternal.ReorderableList.DoLayoutList () (at C:/buildslave/unity/build/Editor/Mono/GUI/ReorderableList.cs:372)
Ink.UnityIntegration.InkInspector.DrawIncludedFiles () (at Assets/Plugins/Ink/Editor/Ink Inspector/Ink Inspector/InkInspector.cs:251)
Ink.UnityIntegration.InkInspector.OnInspectorGUI () (at Assets/Plugins/Ink/Editor/Ink Inspector/Ink Inspector/InkInspector.cs:173)
Ink.UnityIntegration.ObjectEditor.OnInspectorGUI () (at Assets/Plugins/Ink/Editor/Ink Inspector/Ink Inspector/ObjectEditor.cs:33)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1231)
UnityEditor.DockArea:OnGUI()

[some_ink_file.txt](https://github.com/inkle/ink-unity-integration/files/254367/some_ink_file.txt)
[state.txt](https://github.com/inkle/ink-unity-integration/files/254366/state.txt)
[main.txt](https://github.com/inkle/ink-unity-integration/files/254365/main.txt)

**Comment by Horatio-Blackwood** [comment]
If you guys want/need more info on this, please let me know - I'd be happy to support getting this bug fixed, as it affects my actual ink project in the same way as it does these sample files.  If I can find some time I'll try to look into it as well after I've had a chance to familiarize myself with the updated plugin.

Thanks!

**Comment by tomkail** [comment]
Cheers! I'll take a poke now

**Comment by tomkail** [comment]
Hmm, afraid I can't replicate this. It's pretty strange that the bug is occurring in the inspector - I've put in some checks to try to prevent the bug, but I've not yet triggered them.
Noticed your files are .txt, rather than .ink - was that deliberate? They shouldn't compile at all if they're not .ink files.

**Comment by tomkail** [comment]
Alright, I've done my best to make sure that files load properly when they're added while unity is closed. For some reason unity doesn't always process them at the same time when it's just been opened, so it's still possible that it'll not detect file relationships and attempt to compile a child file - if this happens you'll probably get some errors and a JSON file you didn't need - but it should fix itself near instantly when it finds and compiles the last file, so you can ignore them. It's a pretty specific case, and the fixes we've got are a bit hacky, and could lead to other bugs, so unless you find it's still causing you major errors we're going to leave it on the backburner.
I've updated the package and repo - let me know if it's better.

**Comment by Horatio-Blackwood** [comment]
Thanks for looking into this.

The files are .txt because github says it doesn't support files with .ink extensions for uploading to comments, so I have to make them .txt files to upload here.  They are ink files on my local machine.

Your comment of "For some reason unity doesn't always process them at the same time when it's just been opened" I think is the root of this and the other issue referenced above.  Just a hunch, but when  you drop a stack of files into your project as in issue #5 - they don't all arrive at once, rather one at a time which kicks off some events within Unity and cause ink compilations to occur before the rest of the files are there - so at least that one sort of makes sense.

Why it doesn't work on editor startup/loading the Unity project is more of a mystery to me, unless the same thing is happening - files are loaded in one at a time and processing is kicked off as they are loaded rather than once all files are opened.

I'll try out your fixes as soon as I have some time do so and get back with you.  Thanks again!

**Comment by tomkail** [comment]
So when you drop a stack of files in, it should work fine, assuming that unity is already open - that's what I've found so far anyway. If you're finding that's not the case, then I should probably have a look at fixing it. The two solutions we're mulling over are to either:
 - Stop compiling a file if the system realises that a file is no longer needed. Shouldn't affect much, and it should probably do this anyway, but if it compiles quickly then it'll be too late.

- Wait for a few frames before compiling, especially if Unity has recently launched. This feels hacky, but it should fix it. I'm worried that it might introduce more bugs though, especially if we start storing files to recompile in memory, which might get cleared when Unity recompiles (as it does on script change).

**Comment by Horatio-Blackwood** [comment]
When you say you would skip files that are no longer needed do you mean files that aren't part of the file tree that is rooted at the master ink file?

I agree that adding a wait or sleep is pretty hacky, and I bet it would lead to more unexpected behaviors later on.  Anyways, I'll let you know what happens when I try out the fixes.

**Comment by tomkail** [comment]
Yeah, basically. If a file is originally detected as a master file and starts compiling, but is shortly afterwards recognised as a child of a newly detected file, we want to stop it compiling so it doesn't log errors and create an invalid JSON file.

**Comment by Horatio-Blackwood** [comment]
Ooh, yeah that is interesting.  There are probably a few challenges to making that work just right, but that's a decent idea.  Definitely worth a bit of consideration.

**Comment by Horatio-Blackwood** [comment]
Tom,

Just re-ran this test with 0.3.4 Hotfix 2 and it worked brilliantly!

Really digging the new Inspector options (listed include files w/select buttons) not sure how I'll use them, but I like that the files know if they are a master or sub-file and that you can navigate between them.  Should be useful for future debugging as well, as this gives you an indicator of how the system believes the ink files are arranged.

Closing this bug as it is resolved by v0.3.4 Hotfix 2 of ink-unity-integration.

Great job!
