### ISSUE TITLE
Loads of variable compile errors

### ISSUE THREAD

**Issue by Zoroarrkk** [inkle/ink-unity-integration#64]
I've just downloaded the plugin, having used Inky and the Ink language to create a game. I was hoping to use Unity to make the game playable on Android and IOS (Not even sure if that's possible) but as I put my ink and json file into Unity, I'm getting a lot of "unresolved variable" errors, despite it working just fine in the Inky program and as a HTML file. What do I need to do to fix this?

**Comment by tomkail** [comment]
Hmm, that's a new one. Can you tell me where the error is coming from? Is
this on compile, or at runtime?

**Comment by Zoroarrkk** [comment]
On the compile. I go onto the Inspector tab and it's just littered with errors from my variables. As far as I'm aware, it's all the temp variables I used, if that helps. 
![capture](https://user-images.githubusercontent.com/39404205/40228375-08fbb15e-5a89-11e8-8288-68bd86d70c12.PNG)

**Comment by tomkail** [comment]
Hmm, can you send your project over? I'll take a look. Try tom.kail at
inklestudios.com

**Comment by Zoroarrkk** [comment]
Sent ;)

**Comment by Zoroarrkk** [comment]
Also if you need the Unity version, it's 2017.3.0f3
