### ISSUE TITLE
Remove separate Inklecate files for different platforms and use Compiler.dll directly

### ISSUE THREAD

**Issue by KumoKairo** [inkle/ink-unity-integration#65]
EDIT: Original intent of the issue has changed 

~~We've been experiencing this since we've started using Ink. It sometimes locks *.ink for some time and it's impossible to move a file (rarely needed) or change the contents (needed all the time). It usually unlocks after a few "save" tries, but usually takes up to a minute.
Happens on Windows btw, didn't test in on Mac~~

I just wanted to ask if it's a known problem and we're not the only ones who experience it.

**Comment by KumoKairo** [comment]
I have some thoughts on replacing the constant Update method that checks the files with a reactive version that uses AssetPostprocessor (https://docs.unity3d.com/2018.1/Documentation/ScriptReference/AssetPostprocessor.OnPreprocessAsset.html), so it doesn't constantly lock the file "behind the scenes"

**Comment by tomkail** [comment]
Sounds sensible, feel free to try it out!

**Comment by KumoKairo** [comment]
I did some research and it turned out that in already uses this AssetPostprocessorFunctionality to make it know that the file is updated https://github.com/inkle/ink-unity-integration/blob/master/Assets/Plugins/Ink/Editor/Compiler/Auto%20Compiler/InkPostProcessor.cs#L25
It turned out to be more elaborate than just calling a "Compile" function somewhere as it has to build up a queue of files that have to be compiled by a separate process (that's what processes are for, right?).

@tomkail as I can see, the compiler itself is written in C# https://github.com/inkle/ink/tree/master/compiler
Is there a reason why it's shipped as separate compiled libraries for each platform? Is it needed just to create separate processes that allow compiling in background?

**Comment by KumoKairo** [comment]
@joethephish I've been tinkering a bit with the compiler code and it seems that it doesn't have any critical "modern" C# stuff. It's mostly extension methods for joining strings from Lists and automatic conversion from Lists of objects to Lists of string representation of those objects. 
**I've been able to hook up the compiler right from sources inside Unity and call a "Compile" method on a compiler using an old 3.5 .NET version.** 
![image](https://user-images.githubusercontent.com/2943071/40740735-4cda62f8-6452-11e8-8c22-466cb6cac44d.png)

I've been also looking at how the compilation process is handled internally, and it seems that it uses Inklecate command line tool instead of the Compiler class directly (I mean using this https://github.com/inkle/ink/blob/master/compiler/Compiler.cs#L44 instead of using Inklecate with this https://github.com/inkle/ink-unity-integration/blob/master/Assets/Plugins/Ink/Editor/Compiler/InkCompiler.cs#L203)
So you just drop in a compiler dll, and boom, use it's methods directly. No need for separate command line tools for each separate platform (Mac, Win, Linux), no need to fire up new process, works with any Unity version

**Comment by joethephish** [comment]
Weird! I definitely had some compile issues with some of my Parse method calls in the past, I think it was something to do with ambiguity without specifying explicit generic types on method calls, which the compiler said weren't available in my C#/.NET version. But maybe something else wasn't set up correctly on my machine, or it was an even older version of Unity at the time?

(Also, the Compiler class is a new thing that I refactored out from inklecate to make this stuff easily, great to hear it worked!)

Either way, fantastic to hear that's working for you, and we'd be very interested in a pull request for it!

**Comment by KumoKairo** [comment]
> Weird! I definitely had some compile issues with some of my Parse method calls in the past,

Yes, I have changed some 50 lines of code with ambiguous or nonexistent APIs between strings and objects. It required using some Linq statements (which are easily replaced with hardcoded methods if Linq bothers you) and conversion between collections.

> Also, the Compiler class is a new thing that I refactored out from inklecate to make this stuff easily

Yeah, I seem to be lucky to get to Ink right at this point in time where the "tinkering" part is minimal :)

> Either way, fantastic to hear that's working for you, and we'd be very interested in a pull request for it!

I will double and tripple check that it's working exactly as it was and will begin a refactoring process. As the example from my previous comment is just a quick and dirty check-that-it-just-works and is not nearly as automatic and user friendly as the current solution.

I will rename this issue for now as it doesn't represent the solution to the "locked files" anymore

**Comment by joethephish** [comment]
Hmmmmm. So, depending on exactly what the changes look like, I *may* prefer not to change them since we can drop support for old Unity soon anyway. For some parts of the parsing code I'd rather keep the expressiveness. But it all depends on what exactly the changes looks like; would you mind emailing me with some examples of lines you've changed so I can see? joe at inkle studios dot com. Thanks!

**Comment by KumoKairo** [comment]
Done. Be sure to check the spam folder as I have included image links

**Comment by KumoKairo** [comment]
So we have integrated this solution into our workflow, it works good and all (we have found no issues with it yet). But there's a small caveat - somehow calling a plain C# version of the compiler results in a slightly different JSON. It plays just the same (no differences from the user's perspective), but if compared with the "old" compiled version, it shows that outputs are not identical. As I can't really dig into compiled JSON and reason about it, I will post the old and new versions here so @joethephish or @tomkail can tell if there's something wrong with it.
Old one: https://gist.github.com/KumoKairo/5c3940598250e38e7f20dfdfb3cfc85e
New one: https://gist.github.com/KumoKairo/1c663661e8039701f1dff8fede1753b0
It's best compared with a per-symbol highlighter like this one: https://text-compare.com/

**Comment by joethephish** [comment]
Iiiinteresting! Could you try turning on/off the `countAllVisits` option and see if it makes a difference? i.e.:

`new Compiler(inkSource, new Options { countAllVisits = true/false })`

**Comment by KumoKairo** [comment]
Yes, setting `countAllVisist` to `true` yields identical results to the old one.

I have missed that the `-c` option is hardcoded inside the `InkCompiler` https://github.com/inkle/ink-unity-integration/blob/master/Assets/Plugins/Ink/Editor/Compiler/InkCompiler.cs#L221
and have misread it as an "input file" (I wondered why input file is set with `-c`, shame on me)
I have also noted that this option is not included in the InkSettings asset, so I have totally skipped all options (as there's direct control over input-output files right in code, no need to pass anything related to files to the Compiler).

**Comment by joethephish** [comment]
Yeah, the Compiler (and its Options class) is brand new. InkSettings pre-dates that stuff. countAllVisits is an option I occasionally forget about, it's a very specific option that we always have switched on (and we always need) but probably isn't needed for the majority of games, and makes a difference to the save file size.

**Comment by KumoKairo** [comment]
So everything is OK now. I will pull-request the initial changes to the main Ink repo (make the compiler compatible with .NET 3.5) and it will serve as a starting point to further improvements. 

We have stripped out the separate process / separate thread code as our Ink stories usually take a blink to compile and we don't need to run it in background to check for the compilation timeout. But this code is surely needed to cover more general cases, so we can't just submit our Ink-Unity-Integration code as it is.
