### ISSUE TITLE
Welding to choice output concatenates without space.

### ISSUE THREAD

**Issue by Malkyne** [inkle/ink-unity-integration#66]
If I put a weld `<>` at the end of a line, and follow that up with some choices, this _almost_ does what I would expect.  It neatly omits the linefeed from the end of the text provided by `ContinueMaximally` -- which is great!  What is _not_ so great is that it fails to put any space at the end of the line, so my words end up running together.

For instance, if I have:

```
Hi, my name is <>
* John
* Paul
* George
* Ringo
```

...and I select "Paul," this would result in:

> Hi, my name isPaul

As a workaround, for now, I can manually look for lines that end in a non-whitespace character, and plunk a space in there.  It's ugly, but I think it will get the job done.  I just wanted to send a note along, in case it helps.

**Comment by joningold** [comment]
I have a feeling we’ve never considered doing that. So it’s dropping the
line feed and then trimming the result as it normally would. I think your
soln makes sense; if we were to support it it’s pretty much what we’d have
to do anyway!

Jon
