### ISSUE TITLE
Compile Ink with Null InkFile results in a NullReferenceException

### ISSUE THREAD

**Issue by KumoKairo** [inkle/ink-unity-integration#67]
https://github.com/inkle/ink-unity-integration/blob/master/Assets/Plugins/Ink/Editor/Compiler/InkCompiler.cs#L193

We only get into this branch if `inkFile` is `null`. We then try to output its property `inkFile.filePath`. Accessing a property of a `null` objects results in a `NullReferenceException`. Possible solution - remove any file-related data from the log.

**Comment by tomkail** [comment]
Oh good catch! I’ll fix that up.
