### ISSUE TITLE
Does not work after build

### ISSUE THREAD

**Issue by Barschti** [inkle/ink-unity-integration#68]
Hey,

first, i have nearly no experience with unity. So do not expect some obvious knowledge ^^

I imported the ink-unity-integration to unity and found the example. When I click the play-button inside unity it works and i can cklick through the story. But when i do a build for windows, it only shows the blue background and no text appear. Same with build for android.

I use the 0.8.1 version and unity 2018.1.5f1 personal.

I have the same issue (the text does not appear) with these two:
https://github.com/abroder/blot 
https://github.com/inkle/the-intercept

Any ideas what could be the problem? I'm completely new and just want to let it show my story ^^

EDIT: Just saw, that support for Unity 2017 was recently added. Nothing for 2018 ... will test with 2017

**Comment by tomkail** [comment]
Hey, I’ve just tested and it worked fine for me. Is the demo scene the
first scene in the build settings?

**Comment by Barschti** [comment]
Yes. I just uninstalled 2018 and installed 2017.4.3. There it worked. Do you use 2017 or 2018?

**Comment by tomkail** [comment]
Im on 2018.1.4f1. Very weird!

**Comment by tomkail** [comment]
Yup! Google should help with that bit

**Comment by Barschti** [comment]
after going further back to 5.3.4 the intercept also works fine

hmm ... my plan is an android-game wirh my own story. are there some must-have-features in 2017 or 2018 or should i stay with 5.3.4 because it works for me?

**Comment by tomkail** [comment]
Anyone else seeing this? I'll dig in if I need to.

**Comment by KumoKairo** [comment]
@Barschti share a non-working build here, we'll take a look.
Also, post a screenshot of your build settings window (the one in which you press "Build" and "Build & Run")

**Comment by Barschti** [comment]
Hello,

i did an update to 2018.1.6 and now everything works fine... hmm, i dont know. maybe there was there was an error during the first installation causing this bug. 

But thanks for your help guys :) you can close this issue because i cant replicate it anymore.

**Comment by KumoKairo** [comment]
@Barschti you can close it yourself as this issue was created by you (check the close button at the bottom)
