### ISSUE TITLE
Unity 2018 2.0b9 Ink not open

### ISSUE THREAD

**Issue by johnomahen79** [inkle/ink-unity-integration#72]
Cannot edit Ink story if I use the InkUNITY Integration Package
System returns Unable to open Assets/Plugins/Ink/Example/Ink/story.ink
If i edit the json then Visual Studio 2017 opens up correctly. 

If I create a new project and drag and drop an old ink project using the file explorer (not using Integration Package), I can at least edit the ink file but get compilation errors.

Any suggestions.

**Comment by tomkail** [comment]
I’m gonna need a bit more info here. You can’t open it in what? Is this
when you double click it? What complication errors? What version of
unity/ink?

**Comment by johnomahen79** [comment]
Versions:  Unity is 2018.2.0b9
                                UnityInkIntegration0.8.1

Click on the story.ink and error is “Unable to open Assets/Plugins/Ink/Example/Ink/story.in: Check external application preferences

Go to external tools in preferences and Visual Studio 2017 Community Edition chosen; Editor attaching checked


What more can I send you?

John O

John Omahen
Cell: 615-289-2604

**Comment by tomkail** [comment]
Oh so it’s just not opening on double click? If you set your os’s default
program for .ink files it should work - or else just open it from your file
explorer.

**Comment by johnomahen79** [comment]
Okay..thanks

John Omahen
Cell: 615-289-2604
