### ISSUE TITLE
"Thaks for using Ink" after build is unreadable on dark Unity Editor theme

### ISSUE THREAD

**Issue by KumoKairo** [inkle/ink-unity-integration#75]
![image](https://user-images.githubusercontent.com/2943071/46263012-3ab7b000-c512-11e8-87bd-caef67149085.png)
Top message is the default "blue", lower is some lighter value.
The way to address this issue is to add a conditional based on [`EditorGUIUtility.isProSkin`](https://docs.unity3d.com/ScriptReference/EditorGUIUtility-isProSkin.html) (works since Unity 3.5)
```
var color = EditorGUIUtility.isProSkin ? "#3498db" : "blue";
Debug.Log("<color="+ color +">Thanks for using ink....</color>");
```

**Comment by tomkail** [comment]
Ha good idea :) I’ll copy that in
