### ISSUE TITLE
How do I load random stories?

### ISSUE THREAD

**Issue by paologambardella** [inkle/ink-unity-integration#78]
I would like to load a story from a folder, and I am doing something like:

```
private TextAsset inkAsset;

inkAsset = Resources.Load<TextAsset>("Ink/Story_01");
```

after this inkAsset is null. How can I solve this?

**Comment by tomkail** [comment]
I think the path needs an extension?

**Comment by paologambardella** [comment]
No, Resource.Load doesn't want an extension.
