### ISSUE TITLE
Compiling for Mobile iOS/Android

### ISSUE THREAD

**Issue by beachgrub** [inkle/ink-unity-integration#82]
Has anyone built ink into a mobile application?  It seems like the core engine should work but it looks like because they put all the editor tools in the main project, the Unity project will not build for iOS/Android.

Get this error:
ArgumentException: The Assembly ink-engine-runtime is referenced by ink_compiler ('Assets/Plugins/Ink/Inklecate/ink_compiler.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:154)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:194)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by beachgrub** [comment]
It appears deleting all but the Ink runtime allow it to be compiled for mobile.

**Comment by tomkail** [comment]
Apologies for this - that'll have fixed it, as would deleting the runtime DLL (since it conflicts with the source code, I believe). I've disabled the DLL by default on the latest release
