### ISSUE TITLE
Choices diverting to wrong knots

### ISSUE THREAD

**Issue by MarianaCacique** [inkle/ink-unity-integration#90]
Hey! I'm prototyping a narrative game using inky-unity integration. It seemed to be going fine, but after adding my lastest ink file, I noticed the choices are diverting to the wrong knots. 
What is happening is that I have passages 1>2>3>4>5>6>7 in inky and it goes on the right order there. In Unity it's going 1>2>4>5>3>4>5>7.
This is the function I'm using for the choices/diverting:
![image](https://user-images.githubusercontent.com/33615165/65178428-8c9c6300-da0d-11e9-93e9-dbc6c1ea92bc.png)

Thank you for any help, I really need it!

**Comment by tomkail** [comment]
Hmm that’s weird, but I’ll need more information. Simply making choices
should be rock solid so I imagine there’s something else going on.
Can you send over the file?

**Comment by MarianaCacique** [comment]
Here is the ink file!
[VerticalSlice.zip](https://github.com/inkle/ink-unity-integration/files/3628243/VerticalSlice.zip)

**Comment by tomkail** [comment]
Hate to say it, but it all seems fine on my end. It runs as Id expect from
what I can see in inky and unity.
I’d try recompiling it in unity, but it should do that automatically when
any changes are made.
Can you explain what you mean by the numbering?

**Comment by MarianaCacique** [comment]
The numbering is from top to bottom. For example, it means it skips ballroom_div1 between ballroom and ballroom_div2, but after gideon you go to ballroom_div1, not gideon_div1.
It's working fine in inky, that's why I'm confused.

**Comment by tomkail** [comment]
Right yeah that’s what I assumed.
I tested on the development branch but that shouldn’t make any difference;
do make sure you’re on the latest version though.
Other than that, I’d start cutting things out until you find the smallest
reproduction, it might help work out what’s going on?
Can you share more details? None of it should matter but unity
version/package version/where you’re testing (play mode/editor window) ect.

**Comment by MarianaCacique** [comment]
I tried changing the names(in case it was something about the naming convention), but it didn't work.
Here is some info:
Unity version: 2019.2.3f1
Ink Unity Integration version: 0.9.1 
It works fine in the Ink Player and in Inky. In Playmode and in the build it doesn't work.
![image](https://user-images.githubusercontent.com/33615165/65188402-320e0180-da23-11e9-87fe-4dfb734d69c2.png)
Here is the code that assigns the choice to the buttons, just in case I'm doing it wrong.

**Comment by MarianaCacique** [comment]
Managed to fix it!! The problem was that one of choice button was permanent in the scene(due to gameplay reasons), and when adding the OnClickChoiceButton to its OnClick delegate, I didn't clear all listeners (because it was not needed for any other button). Thank you for your patience!!

**Comment by tomkail** [comment]
Haha well done :)
