### ISSUE TITLE
I need help with splitting lines for a database.

### ISSUE THREAD

**Issue by ashfidable** [inkle/ink-unity-integration#94]
I don't know how often we get replies here. But I am trying to keep database of my Ink files in Scriptable Object. The problem is I have list of string where I want to store my lines before Choices. Individually. I get it .Continue() handles that but its not the same for stuff like that. Can anyone help me?
I can do 
for(int i = 0; i < LINESIHAVE; i++){
Lines.Add(Story.Continue());
}
Kinda thing but then I have to mention Lines by hand, is there no way I can know the count of lines before Choices?

**Comment by tomkail** [comment]
Try our discoed for help using the plugin!
https://discord.gg/tD8Am2K
