### ISSUE TITLE
Getting an exception "Choice out of range"

### ISSUE THREAD

**Issue by darkmajki** [inkle/ink-unity-integration#96]
Ok so I've tried any solution I could think of and I still get the same error.  I was getting the error even with the default 80 days story. Basically I click on a button to make a choice and I get the error choice out of range which usually stops the story from going on. and just sets the game object to be inactive which it should but only when there are no more options while it clearly has more options.
Here one sample text from which I get the error, although even non looping one throw an exception.
I'm sorry in advance, I don't know how to format the ink text in here. But it does work inside the ink editor.
`VAR n = 0
VAR resetEnemyNumber = true
VAR enemy_number = 5
===fight_multiple_enemies===
{resetEnemyNumber: 
    ~enemy_number = RANDOM(3, 5)
}
~resetEnemyNumber = false
{
    -n <= enemy_number:
        +[Fight them]
        ~temp entity = GetQuestEncounterEntity()
        ~StartBattleImmediately(entity)
        ~n+=1
        //There are {enemy_number - n} enemies left.
        //+[Continue fighting them]
        ->fight_multiple_enemies
        +[Flee]       ->End_STORY
    -else:
        +[END]
        ~n=0
        ~resetEnemyNumber = true
        {SendQuestMessage("DealtWithThreat", GetQuestEncounterEntity())}
        ->End_STORY
}`
And here is the code I use even though is more or less adapted version of one of the samples you have.
`using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using Ink.Runtime;
using System.Collections.Generic;

// This is a super bare bones example of how to play and display a ink story in Unity.
public class InkFileUI : MonoBehaviour
{

    void Awake()
    {
        // Remove the default message
        //RemoveChildren();
        StartStory();
    }

    // Creates a new Story object with the compiled story which we can then play!
    void StartStory()
    {
        story = new Story(inkJSONAsset.text);
        //you need to define it in the ink file too
        //External functions emitted
    }
    public void AddNewTextFromKnot(string knotName)
    {
        story.ChoosePathString(knotName);
        RefreshView();
        //story.Continue();
    }
    // This is the main function called every time the story changes. It does a few things:
    // Destroys all the old content and choices.
    // Continues over all the lines of text, then displays all the choices. If there are no choices, the story is finished!
    void RefreshView()
    {
        // Remove all the UI on screen
        //RemoveChildren ();
        if(story.canContinue)
        {
            DeactivateChoices();
            dialogueTXT.gameObject.SetActive(true);
            // Read all the content until we can't continue any more
            
            // Continue gets the next line of the story
            string text = story.ContinueMaximally();

            // This removes any white space from the text.
            text.Trim();
            // Display the text on screen!
            CreateContentView(text);
            Debug.Log(text);
            StartCoroutine(TypeText(text));
            
        }
    }
    // When we click the choice button, tell the story to choose that choice!
    void OnClickChoiceButton(Choice choice)
    {        
        story.ChooseChoiceIndex(choice.index);
        RefreshView();
    }
    float t;
    private void Update()
    {

        if (choicesCanBeSeen)
        {
            choicesCanBeSeen = false;
        }
    }
    void ShowChoices()
    {
        // Display all the choices, if there are any!
        Debug.Log("Curr choices " + story.currentChoices.Count);
        
        if (story.currentChoices.Count > 0)
        {
            for (int i = 0; i < story.currentChoices.Count; i++)
            {

                //dialogueTXT.gameObject.SetActive(false);
                Choice choice = story.currentChoices[i];
                Debug.Log("CHOICEs are " + story.currentChoices[i].text);
                Button button = CreateChoiceView(choice.text.Trim(), i);
                // Tell the button what to do when we press it
                button.onClick.AddListener(delegate {
                    OnClickChoiceButton(choice);
                });
            }
        }
        // If we've read all the content and there's no choices, the story is finished!
        else
        {
            gameObject.SetActive(false);            
        }
        
    }
    // Creates a button showing the choice text
    void CreateContentView(string text)
    {
        dialogueTXT.gameObject.SetActive(true);
        dialogueTXT.text = text;
    }
    IEnumerator TypeText(string message)
    {
        for (int i = 0; i < message.Length; i++)
        {            
            dialogueTXT.text = message.Substring(0, i);            
            SoundManager.Instance.PlayCyoaLetterSoundSound();
            yield return new WaitForSeconds(letterPause);

        }
        yield return new WaitForSeconds(0.5f);
        ShowChoices();
        choicesCanBeSeen = true;

    }
    void DeactivateChoices()
    {
        for (int idx =  choices.Count-1; idx >= 0; idx--)
        {
            choices[idx].gameObject.SetActive(false);
        }

    }
    // Creates a button showing the choice text
    Button CreateChoiceView(string text, int idx)
    {

        choices[idx].GetComponentInChildren<Text>().text = text;
        choices[idx].gameObject.SetActive(true);
        return choices[idx];
    }

    bool choicesCanBeSeen = false;
    public float letterPause = 0.2f;
    [SerializeField]
    private TextAsset inkJSONAsset;
    private Story story;

    [SerializeField]
    private List<Button> choices;
    //[SerializeField]
    //private Canvas canvas;

    // UI Prefabs
    [SerializeField]
    private Text dialogueTXT;
    //[SerializeField]
    //private Button buttonPrefab;
}`
Did I change something and with that made a big mistake? Or the problem lies somewhere else? Recently I've read that ink doesn't support changes of state from the ink file so maybe it has something to do with it?

Any help would be appreciated.

**Comment by tomkail** [comment]
I don’t have time to check this properly I’m afraid, but I’d guess that
your choice buttons reference choices that no longer exist. Try playing
your story in the ink player editor window; if that works then it’ll be
your code that’s wrong.

**Comment by darkmajki** [comment]
Thank you for your response.
Yeah I figured that the choice doesn't exist anymore somehow, but couldn't pinpoint the issue, thought it might be a problem that you guys faced before. I did test it out already on the ink player and the inky text editor and there were no problems. I guess I will close the issue.

Thank you for your help and good luck in your next game whatever it might be.
