### ISSUE TITLE
Internal to public request

### ISSUE THREAD

**Issue by joaobsneto** [inkle/ink-unity-integration#97]
I want to add a function to my game that listen to all variables change and to have a response based on variable name. So, listen to this deletage in VariablesState from Story instance would be what I want, but it's not accessible. Is there a reason for this to be internal?

`
internal delegate void VariableChanged(string variableName, Runtime.Object newValue);
internal event VariableChanged variableChangedEvent;
`

Could it be changed to public? Or there is another way to access this event?

**Comment by facelesspanda** [comment]
somewhat, through `ObserveVariable` and `ObserveVariables`. They listen to explicit given variable names. There's no way to listen to all variables.

**Comment by tomkail** [comment]
Yup, this is the correct solution. It’s what we use. Does this solve your
problem?

**Comment by joaobsneto** [comment]
I don't think so, I would like to listen to all variables.
In my game, the variables name follow some patterns and I would parse the variable name to know what it represents. When player learn something or there is any important state change, I want to notify in the UI.
There are a lot of variables and it would be a hursle to register all the variables on ObserveVariable, but it's not impossible. It seems more intuitive to listen to all variables than to get all variables at the start and register the function in ObserveVariable, because, I would have to parse the variable name anyway, even if a specific fuction was set for each type of variable.

**Comment by joethephish** [comment]
This isn't something we'd consider changing in the engine, but you're welcome to make a little hack to the source to support this behaviour on your end!

**Comment by joaobsneto** [comment]
Thanks!

**Comment by joethephish** [comment]
Oh, and we recommend just including the engine source direct in your game, in which case you don't have to change anything, since internal-marked methods will just work anyway. You can just treat it as private API that isn't *intended* to be used directly, but you can do so if you know what you're doing.

**Comment by joaobsneto** [comment]
I do that, but my code must be in Ink's namespace to access internal, which is not practical.

I see a concern about making variableChangedEvent public is that if the user override the delegate or remove the method the handles the internal Ink behavior, it would break Ink. Maybe adding an extra public event would be safier.

**Comment by facelesspanda** [comment]
`internal` should work if it's within the same assembly, it has nothing to do with namespace.

**Comment by joaobsneto** [comment]
Hummm... So the suggestion is to put Ink code inside my game assembly? I'll do that! Thanks, guys!
